---

- name: Install packages
  yum: name=libselinux-python state=present

- name: Disable SELinux at next reboot
  selinux:
    state: disabled

- name: Set SELinux in permissive mode until the machine is rebooted
  command: setenforce 0
  ignore_errors: true
  changed_when: false

- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Create kubeadm sysctl file
  copy: src=90-kubeadm.conf dest=/etc/sysctl.d/90-kubeadm.conf

- name: Set sysctl settings
  shell: sysctl --system

- name: Add Docker yum repository
  yum_repository:
    name: Docker
    description: Docker Repository
    file: docker
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg

- name: Create kubernetes yum repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: no
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg 
    enabled: yes

- name: Install packages
  yum: name={{ item }} state=present
  with_items:
  - docker
  - kubeadm

- name: Enable and start docker
  systemd: state=started enabled=yes name=docker

- name: Enable and start kubelet
  systemd: state=started enabled=yes name=kubelet






